source 'https://rubygems.org'
ruby '2.3.3'
gem 'bundler', '1.16.1'
gem 'jekyll'
gem 'rack-jekyll'
gem 'rake'
gem 'rack-cache'
gem 'dalli'
gem 'kgio'
gem "memcachier"
gem 'jekyll-theme-minimal'
group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-paginate-v2'
  gem 'jekyll-include-cache'
  gem 'jekyll-last-modified-at'
  gem 'jekyll-redirect-from'
end
